import Amplify, { Auth, Logger } from 'aws-amplify';
import XR from '@aws-amplify/xr';

import scene1Config from './sumerian-exports.json'; // This file will be generated by the Sumerian AWS Console
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

window.LOG_LEVEL = 'DEBUG';

// Hard code a username/password, change this to prompt users to login
var username = "test1";
var password = "yy4P2_bp";

/*
Auth.signUp({
    username,
    password,
    attributes: {
        email: "julbrigh+sumerian@amazon.com"
    },
    validationData: []  //optional
  })
  .then(data => console.log(data))
  .catch(err => console.log(err));
*/

// Sumerian private scene requires an auth idenity

Auth.signIn(username, password)
  .then(user => {
    console.log('got user', user)

    XR.configure({ // XR category configuration
      SumerianProvider: { // Sumerian specific configuration
        region: 'ap-southeast-2', // Sumerian region
        scenes: {
          "scene1": { // Friendly scene name
            sceneConfig: scene1Config,
            publishParamOverrides: { thingName: "xxx" } // Scene configuration from Sumerian publish
          }
        },
      }
    });

    const progressCallback = (progress) => {
      console.log(`Sumerian scene load progress: ${progress * 100}%`);
    }
    const sceneOptions = {
        progressCallback
    }
    XR.loadScene("scene1", "sumerian-scene-dom-id", sceneOptions).then(res => {
      console.log('loaded', res);
      XR.start("scene1");
    }, err => {
      console.log('failed to load', err);
    })

  })
  .catch(err => {
    console.log('auth error', err)
  });
