// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cfd23821-16ed-4794-9a34-03902e228aa1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_m16dGrNXH",
    "aws_user_pools_web_client_id": "q7idqalhjqmfct1euvel7nsk",
    "aws_content_delivery_bucket": "virtual-concierge-amplify-us-east-1",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://virtual-concierge-amplify-us-east-1.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
